apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: readwriteonce-com-tls
spec:
  secretName: readwriteonce-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: readwriteonce.com
  dnsNames:
    - readwriteonce.com
    - www.readwriteonce.com